import { OverWorldMaps } from '@lib/models/overworld-map';
import { PERSON_ANIMATIONS, PERSON_DIRECTION_UPDATES } from './game-object-person';
import { BASE_ANIMATION_FRAME_LIMIT, BASE_FRAME_COORDS } from './game-objects';

// TODO: implement zod validation when this object come from an external json
export const OVERWORLD_MAPS: OverWorldMaps = {
  DemoRoom: {
    id: 'DemoRoom',
    lowerSrc: '/images/maps/DemoLower.png',
    upperSrc: '/images/maps/DemoUpper.png',
    gameObjects: {
      hero: {
        id: 'hero',
        x: 5,
        y: 6,
        type: 'person',
        isPlayerControlled: true,
        movingProgressRemaining: 0,
        direction: 'down',
        directionUpdate: PERSON_DIRECTION_UPDATES,
        src: '/images/characters/people/hero.png',
        hasShadow: true,
        animations: PERSON_ANIMATIONS,
        currentAnimation: 'idle-down',
        currentAnimationFrame: 0,
        animationFrameLimit: BASE_ANIMATION_FRAME_LIMIT,
        animationFrameProgress: 0,
        currentFrameCoords: BASE_FRAME_COORDS,
      },
      npc1: {
        id: 'npc1',
        x: 7,
        y: 9,
        type: 'person',
        isPlayerControlled: false,
        movingProgressRemaining: 0,
        direction: 'down',
        directionUpdate: PERSON_DIRECTION_UPDATES,
        src: '/images/characters/people/npc1.png',
        hasShadow: true,
        animations: PERSON_ANIMATIONS,
        currentAnimation: 'idle-down',
        currentAnimationFrame: 0,
        animationFrameLimit: BASE_ANIMATION_FRAME_LIMIT,
        animationFrameProgress: 0,
        currentFrameCoords: BASE_FRAME_COORDS,
      },
    },
  },
  Kitchen: {
    id: 'Kitchen',
    lowerSrc: '/images/maps/KitchenLower.png',
    upperSrc: '/images/maps/KitchenUpper.png',
    gameObjects: {
      hero: {
        id: 'hero',
        x: 3,
        y: 5,
        type: 'person',
        isPlayerControlled: true,
        movingProgressRemaining: 0,
        direction: 'down',
        directionUpdate: PERSON_DIRECTION_UPDATES,
        src: '/images/characters/people/hero.png',
        hasShadow: true,
        animations: PERSON_ANIMATIONS,
        currentAnimation: 'idle-down',
        currentAnimationFrame: 0,
        animationFrameLimit: BASE_ANIMATION_FRAME_LIMIT,
        animationFrameProgress: 0,
        currentFrameCoords: BASE_FRAME_COORDS,
      },
      npcA: {
        id: 'npcA',
        x: 9,
        y: 6,
        type: 'person',
        isPlayerControlled: false,
        movingProgressRemaining: 0,
        direction: 'down',
        directionUpdate: PERSON_DIRECTION_UPDATES,
        src: '/images/characters/people/npc2.png',
        hasShadow: true,
        animations: PERSON_ANIMATIONS,
        currentAnimation: 'idle-down',
        currentAnimationFrame: 0,
        animationFrameLimit: BASE_ANIMATION_FRAME_LIMIT,
        animationFrameProgress: 0,
        currentFrameCoords: BASE_FRAME_COORDS,
      },
      npcB: {
        id: 'npcB',
        x: 10,
        y: 8,
        type: 'person',
        isPlayerControlled: false,
        movingProgressRemaining: 0,
        direction: 'down',
        directionUpdate: PERSON_DIRECTION_UPDATES,
        src: '/images/characters/people/npc3.png',
        hasShadow: true,
        animations: PERSON_ANIMATIONS,
        currentAnimation: 'idle-down',
        currentAnimationFrame: 0,
        animationFrameLimit: BASE_ANIMATION_FRAME_LIMIT,
        animationFrameProgress: 0,
        currentFrameCoords: BASE_FRAME_COORDS,
      },
    },
  },
};
